/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetracker;

import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Time;

/**
 *
 * @author Sijan Bhandari
 */
public class ConfigPanel extends javax.swing.JFrame {

    /**
     * Creates new form ConfigPanel
     */
    public ConfigPanel() {
        initComponents();
        //set location to lower right corner
        this.setLocation(Toolkit.getDefaultToolkit().getScreenSize().width - this.getWidth()-50, Toolkit.getDefaultToolkit().getScreenSize().height - this.getHeight()-50);
        this.setAlwaysOnTop(true);
        //set frame to transparent
        this.setBackground(new Color(255, 255, 255, 0));
        this.setVisible(true);
        rSTextFieldMaterial1.setText(String.valueOf(TimeCounter.timeLimit/1000/60));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new timetracker.RoundPanel();
        rSButtonRoundEffect2 = new rojeru_san.rsbutton.RSButtonRoundEffect();
        rSButtonRoundEffect1 = new rojeru_san.rsbutton.RSButtonRoundEffect();
        rSTextFieldMaterial1 = new RSMaterialComponent.RSTextFieldMaterial();
        roundPanel2 = new timetracker.RoundPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Time Editor");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 255, 153));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundPanel1.setBackground(new java.awt.Color(102, 102, 255));

        rSButtonRoundEffect2.setBackground(new java.awt.Color(102, 255, 51));
        rSButtonRoundEffect2.setForeground(new java.awt.Color(102, 102, 102));
        rSButtonRoundEffect2.setText("Submit");
        rSButtonRoundEffect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRoundEffect2ActionPerformed(evt);
            }
        });

        rSButtonRoundEffect1.setBackground(new java.awt.Color(255, 102, 102));
        rSButtonRoundEffect1.setText("Cancel");
        rSButtonRoundEffect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRoundEffect1ActionPerformed(evt);
            }
        });

        rSTextFieldMaterial1.setBackground(new java.awt.Color(102, 102, 255));
        rSTextFieldMaterial1.setForeground(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial1.setCaretColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial1.setColorMaterial(new java.awt.Color(0, 204, 51));
        rSTextFieldMaterial1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial1.setOpaque(false);
        rSTextFieldMaterial1.setPhColor(new java.awt.Color(255, 255, 255));
        rSTextFieldMaterial1.setPlaceholder("Time in Minutes");
        rSTextFieldMaterial1.setSelectionColor(new java.awt.Color(102, 102, 255));

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSTextFieldMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(roundPanel1Layout.createSequentialGroup()
                        .addComponent(rSButtonRoundEffect2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(rSButtonRoundEffect1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSTextFieldMaterial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSButtonRoundEffect2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonRoundEffect1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, 300, 110));

        roundPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dev TimeTracker");

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(roundPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRoundEffect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRoundEffect2ActionPerformed
        try{
            double time = Double.parseDouble(rSTextFieldMaterial1.getText());
            time = time * 60 * 1000;
            System.out.println(time);
            if (time > 0) {
                this.dispose();
                TimeCounter.timeLimit = time;
                //write to time file in user directory
                File file = new File(System.getProperty("user.home") + "\\TimeTracker\\time.txt");
                boolean v=file.getParentFile().mkdirs();
                //write to file
                BufferedWriter writer = new BufferedWriter(new FileWriter(file));
                writer.write(String.valueOf(time));
                writer.close();
            } else {
                rSTextFieldMaterial1.setColorMaterial(new java.awt.Color(255, 0, 0));
            }
        } catch (Exception e) {
            rSTextFieldMaterial1.setColorMaterial(new java.awt.Color(255, 0, 0));
        }
    }//GEN-LAST:event_rSButtonRoundEffect2ActionPerformed

    private void rSButtonRoundEffect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRoundEffect1ActionPerformed
      dispose();
    }//GEN-LAST:event_rSButtonRoundEffect1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfigPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfigPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfigPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfigPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfigPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private rojeru_san.rsbutton.RSButtonRoundEffect rSButtonRoundEffect1;
    private rojeru_san.rsbutton.RSButtonRoundEffect rSButtonRoundEffect2;
    private RSMaterialComponent.RSTextFieldMaterial rSTextFieldMaterial1;
    private timetracker.RoundPanel roundPanel1;
    private timetracker.RoundPanel roundPanel2;
    // End of variables declaration//GEN-END:variables
}
